// ============================================================
// ABHISHEK BOOK DEPOT — Complete Product & Category Data
// ============================================================

export const CATEGORIES = [
  { id: 'books',          name: 'Books',           icon: '📚', color: '#2874F0', bg: '#EBF2FF' },
  { id: 'ncert',          name: 'NCERT Books',     icon: '🎓', color: '#7C3AED', bg: '#EDE9FE' },
  { id: 'stationery',     name: 'Stationery',      icon: '✏️',  color: '#059669', bg: '#ECFDF5' },
  { id: 'copies',         name: 'Copies',          icon: '📓', color: '#D97706', bg: '#FFFBEB' },
  { id: 'registers',      name: 'Registers',       icon: '📒', color: '#DC2626', bg: '#FEF2F2' },
  { id: 'pens',           name: 'Pens & Pencils',  icon: '🖊️',  color: '#0891B2', bg: '#ECFEFF' },
  { id: 'art',            name: 'Art & Craft',     icon: '🎨', color: '#BE185D', bg: '#FDF2F8' },
  { id: 'flowers',        name: 'Flowers',         icon: '🌸', color: '#E11D48', bg: '#FFF1F2' },
  { id: 'toys',           name: 'Toys',            icon: '🧸', color: '#F59E0B', bg: '#FFFBEB' },
  { id: 'games',          name: 'Games',           icon: '🎮', color: '#6D28D9', bg: '#EDE9FE' },
  { id: 'gifts',          name: 'Gifts',           icon: '🎁', color: '#EC4899', bg: '#FDF2F8' },
  { id: 'school',         name: 'School Supplies', icon: '🎒', color: '#2563EB', bg: '#EFF6FF' },
  { id: 'office',         name: 'Office Supplies', icon: '🗂️',  color: '#374151', bg: '#F9FAFB' },
  { id: 'decoration',     name: 'Decoration',      icon: '✨', color: '#D97706', bg: '#FEFCE8' },
];

export const BRANDS = ['Navneet', 'Classmate', 'Natraj', 'Camlin', 'Apsara', 'Luxor', 'Reynolds', 'NCERT', 'S.Chand', 'Oswaal', 'MTG', 'Arihant', 'Faber-Castell', 'Solo', 'Kores', 'Chelpark', 'Pilot', 'Parker', 'Cello'];

const imgBase = (seed, w = 400, h = 400) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const PRODUCTS = [
  // ── NCERT BOOKS ──────────────────────────────────────────
  { id: 1,   name: 'NCERT Mathematics Class 10',         category: 'ncert',      price: 85,   mrp: 120,  discount: 29, rating: 4.8, reviews: 2341, stock: 50,  brand: 'NCERT',      image: imgBase('book1'),   description: 'Official NCERT Mathematics textbook for Class 10. Covers all CBSE curriculum topics with exercises and examples.', tags: ['class 10', 'maths', 'cbse'] },
  { id: 2,   name: 'NCERT Science Class 10',             category: 'ncert',      price: 90,   mrp: 130,  discount: 31, rating: 4.7, reviews: 1987, stock: 45,  brand: 'NCERT',      image: imgBase('book2'),   description: 'Official NCERT Science textbook for Class 10. Physics, Chemistry, Biology all in one.', tags: ['class 10', 'science', 'cbse'] },
  { id: 3,   name: 'NCERT Social Science Class 10',      category: 'ncert',      price: 80,   mrp: 115,  discount: 30, rating: 4.6, reviews: 1654, stock: 40,  brand: 'NCERT',      image: imgBase('book3'),   description: 'History, Geography, Political Science and Economics for Class 10.', tags: ['class 10', 'sst', 'cbse'] },
  { id: 4,   name: 'NCERT English Class 10',             category: 'ncert',      price: 75,   mrp: 105,  discount: 29, rating: 4.5, reviews: 1432, stock: 38,  brand: 'NCERT',      image: imgBase('book4'),   description: 'First Flight and Footprints Without Feet — NCERT English for Class 10.', tags: ['class 10', 'english', 'cbse'] },
  { id: 5,   name: 'NCERT Hindi Class 10',               category: 'ncert',      price: 70,   mrp: 100,  discount: 30, rating: 4.4, reviews: 1123, stock: 35,  brand: 'NCERT',      image: imgBase('book5'),   description: 'Kshitij and Kritika — NCERT Hindi textbooks for Class 10.', tags: ['class 10', 'hindi', 'cbse'] },
  { id: 6,   name: 'NCERT Mathematics Class 9',          category: 'ncert',      price: 82,   mrp: 118,  discount: 31, rating: 4.7, reviews: 2100, stock: 48,  brand: 'NCERT',      image: imgBase('book6'),   description: 'Class 9 NCERT Maths — algebra, geometry, statistics and more.', tags: ['class 9', 'maths', 'cbse'] },
  { id: 7,   name: 'NCERT Science Class 9',              category: 'ncert',      price: 88,   mrp: 125,  discount: 30, rating: 4.6, reviews: 1876, stock: 42,  brand: 'NCERT',      image: imgBase('book7'),   description: 'Class 9 NCERT Science covering matter, motion, biology and more.', tags: ['class 9', 'science', 'cbse'] },
  { id: 8,   name: 'NCERT Mathematics Class 12 Part 1',  category: 'ncert',      price: 95,   mrp: 140,  discount: 32, rating: 4.9, reviews: 3012, stock: 55,  brand: 'NCERT',      image: imgBase('book8'),   description: 'Relations, Functions, Matrices, Determinants and more for Class 12.', tags: ['class 12', 'maths', 'cbse'] },
  { id: 9,   name: 'NCERT Physics Class 12 Part 1',      category: 'ncert',      price: 92,   mrp: 135,  discount: 32, rating: 4.8, reviews: 2765, stock: 50,  brand: 'NCERT',      image: imgBase('book9'),   description: 'Electrostatics, Current Electricity and more — NCERT Physics Class 12.', tags: ['class 12', 'physics', 'cbse'] },
  { id: 10,  name: 'NCERT Chemistry Class 12 Part 1',    category: 'ncert',      price: 88,   mrp: 130,  discount: 32, rating: 4.7, reviews: 2543, stock: 48,  brand: 'NCERT',      image: imgBase('book10'),  description: 'Solid State, Solutions, Electrochemistry — NCERT Chemistry Class 12.', tags: ['class 12', 'chemistry', 'cbse'] },

  // ── COMPETITIVE EXAM BOOKS ────────────────────────────────
  { id: 11,  name: 'Oswaal CBSE Sample Papers Class 10', category: 'books',      price: 299,  mrp: 450,  discount: 34, rating: 4.7, reviews: 3421, stock: 30,  brand: 'Oswaal',     image: imgBase('book11'),  description: 'Latest CBSE sample papers with marking scheme and previous year questions.', tags: ['sample papers', 'class 10', 'cbse'] },
  { id: 12,  name: 'Arihant All-in-One Science Class 10',category: 'books',      price: 349,  mrp: 520,  discount: 33, rating: 4.6, reviews: 2876, stock: 25,  brand: 'Arihant',    image: imgBase('book12'),  description: 'Complete study package with theory, examples, exercises and sample papers.', tags: ['all in one', 'class 10', 'science'] },
  { id: 13,  name: 'MTG Rapid Revision NEET Biology',    category: 'books',      price: 459,  mrp: 699,  discount: 34, rating: 4.8, reviews: 4123, stock: 20,  brand: 'MTG',        image: imgBase('book13'),  description: 'Quick revision guide for NEET Biology with MCQs and important diagrams.', tags: ['neet', 'biology', 'rapid revision'] },
  { id: 14,  name: 'Arihant 40 Days JEE Maths',         category: 'books',      price: 379,  mrp: 560,  discount: 32, rating: 4.7, reviews: 3765, stock: 22,  brand: 'Arihant',    image: imgBase('book14'),  description: '40-day crash course for JEE Main Mathematics with practice questions.', tags: ['jee', 'maths', 'crash course'] },
  { id: 15,  name: 'Lucent General Knowledge 2025',      category: 'books',      price: 199,  mrp: 320,  discount: 38, rating: 4.5, reviews: 5234, stock: 60,  brand: 'Lucent',     image: imgBase('book15'),  description: 'Comprehensive GK book covering Indian history, geography, polity, science and current affairs.', tags: ['gk', 'general knowledge', 'competitive'] },
  { id: 16,  name: 'S.Chand Physics Class 11',           category: 'books',      price: 420,  mrp: 650,  discount: 35, rating: 4.6, reviews: 1987, stock: 18,  brand: 'S.Chand',    image: imgBase('book16'),  description: 'S Chand comprehensive Physics for Class 11 — theory and problems.', tags: ['class 11', 'physics', 'schand'] },
  { id: 17,  name: 'Oswaal Sample Papers Class 12 PCM',  category: 'books',      price: 549,  mrp: 850,  discount: 35, rating: 4.7, reviews: 2876, stock: 15,  brand: 'Oswaal',     image: imgBase('book17'),  description: 'Physics, Chemistry & Maths sample papers bundle for Class 12.', tags: ['class 12', 'pcm', 'sample papers'] },
  { id: 18,  name: 'Arihant Reasoning Book SSC/Bank',    category: 'books',      price: 249,  mrp: 395,  discount: 37, rating: 4.5, reviews: 4321, stock: 35,  brand: 'Arihant',    image: imgBase('book18'),  description: 'Complete reasoning guide for SSC, Banking and other competitive exams.', tags: ['reasoning', 'ssc', 'banking'] },

  // ── STATIONERY ───────────────────────────────────────────
  { id: 19,  name: 'Reynolds 045 Ball Pen (Pack of 10)', category: 'pens',       price: 99,   mrp: 150,  discount: 34, rating: 4.6, reviews: 8765, stock: 200, brand: 'Reynolds',   image: imgBase('pen1'),    description: 'Smooth writing Reynolds 045 ball pens in blue ink. Pack of 10.', tags: ['ball pen', 'blue', 'pack of 10'] },
  { id: 20,  name: 'Cello Gripper Ball Pen (10 Pack)',   category: 'pens',       price: 110,  mrp: 175,  discount: 37, rating: 4.5, reviews: 6543, stock: 180, brand: 'Cello',      image: imgBase('pen2'),    description: 'Ergonomic grip for comfortable writing. Available in blue and black.', tags: ['ball pen', 'gripper', 'cello'] },
  { id: 21,  name: 'Pilot V5 Hi-Tecpoint Pen',           category: 'pens',       price: 60,   mrp: 85,   discount: 29, rating: 4.8, reviews: 4321, stock: 100, brand: 'Pilot',      image: imgBase('pen3'),    description: 'Liquid ink roller pen for precise, smooth writing. Perfect for exams.', tags: ['pilot', 'v5', 'liquid ink'] },
  { id: 22,  name: 'Parker Vector Ball Pen Blue',        category: 'pens',       price: 199,  mrp: 299,  discount: 33, rating: 4.7, reviews: 2134, stock: 50,  brand: 'Parker',     image: imgBase('pen4'),    description: 'Premium Parker ball pen with stainless steel nib. Gift-ready packaging.', tags: ['parker', 'premium', 'gift pen'] },
  { id: 23,  name: 'Natraj HB Pencils (Pack of 20)',     category: 'pens',       price: 59,   mrp: 90,   discount: 34, rating: 4.5, reviews: 5678, stock: 300, brand: 'Natraj',     image: imgBase('pen5'),    description: 'Classic HB pencils with smooth graphite. Ideal for writing and drawing.', tags: ['pencil', 'hb', 'natraj'] },
  { id: 24,  name: 'Apsara Drawing Pencil Set (12 pcs)', category: 'pens',       price: 79,   mrp: 120,  discount: 34, rating: 4.6, reviews: 3456, stock: 150, brand: 'Apsara',     image: imgBase('pen6'),    description: 'Set of 12 drawing pencils ranging from 2H to 6B for artists.', tags: ['drawing pencil', 'art', 'apsara'] },
  { id: 25,  name: 'Faber-Castell Colour Pencils 24',    category: 'pens',       price: 199,  mrp: 320,  discount: 38, rating: 4.8, reviews: 4567, stock: 80,  brand: 'Faber-Castell', image: imgBase('pen7'), description: '24 vibrant shades, comfortable grip, break-resistant leads.', tags: ['colour pencils', '24 shades', 'faber castell'] },
  { id: 26,  name: 'Luxor Ink Pen Set (Pack of 5)',      category: 'pens',       price: 149,  mrp: 220,  discount: 32, rating: 4.4, reviews: 2345, stock: 70,  brand: 'Luxor',      image: imgBase('pen8'),    description: 'Classic fountain-style ink pens. Comes with 5 assorted colors.', tags: ['ink pen', 'luxor', 'pack of 5'] },

  // ── COPIES & REGISTERS ───────────────────────────────────
  { id: 27,  name: 'Navneet Pulse Notebook 200 Pages',   category: 'copies',     price: 59,   mrp: 90,   discount: 34, rating: 4.5, reviews: 7890, stock: 400, brand: 'Navneet',    image: imgBase('note1'),   description: 'Premium quality 200-page ruled notebook with smooth pages.', tags: ['notebook', '200 pages', 'navneet'] },
  { id: 28,  name: 'Classmate Interleaf A4 Notebook',    category: 'copies',     price: 69,   mrp: 100,  discount: 31, rating: 4.6, reviews: 5432, stock: 350, brand: 'Classmate',  image: imgBase('note2'),   description: 'A4 size interleaf notebook with ruled pages. Great for school and college.', tags: ['a4', 'interleaf', 'classmate'] },
  { id: 29,  name: 'Navneet Jumbo Register 500 Pages',   category: 'registers',  price: 149,  mrp: 220,  discount: 32, rating: 4.7, reviews: 3456, stock: 200, brand: 'Navneet',    image: imgBase('note3'),   description: 'Large 500-page register for accounts, records and heavy use.', tags: ['register', '500 pages', 'jumbo'] },
  { id: 30,  name: 'Classmate Science Practical File',   category: 'copies',     price: 79,   mrp: 120,  discount: 34, rating: 4.5, reviews: 2345, stock: 150, brand: 'Classmate',  image: imgBase('note4'),   description: 'A4 size science practical file with graph and plain pages alternating.', tags: ['practical file', 'science', 'classmate'] },
  { id: 31,  name: 'Long Register 200 Pages (Pack 5)',   category: 'registers',  price: 199,  mrp: 299,  discount: 33, rating: 4.4, reviews: 1876, stock: 120, brand: 'Navneet',    image: imgBase('note5'),   description: 'Pack of 5 long-size ruled registers. Ideal for accounts and school use.', tags: ['long register', 'pack of 5', 'wholesale'] },
  { id: 32,  name: 'Navneet A4 Copy (Pack of 10)',       category: 'copies',     price: 299,  mrp: 450,  discount: 34, rating: 4.6, reviews: 4321, stock: 100, brand: 'Navneet',    image: imgBase('note6'),   description: 'Wholesale pack of 10 A4 ruled copies. Best value for schools.', tags: ['a4 copy', 'pack of 10', 'wholesale'] },
  { id: 33,  name: 'Drawing Book A3 (25 Sheets)',        category: 'copies',     price: 55,   mrp: 80,   discount: 31, rating: 4.5, reviews: 2876, stock: 200, brand: 'Navneet',    image: imgBase('note7'),   description: 'Thick A3 drawing pages for school art projects.', tags: ['drawing book', 'a3', 'art'] },

  // ── ART & CRAFT ──────────────────────────────────────────
  { id: 34,  name: 'Camlin Kokuyo Acrylic Colour Set',   category: 'art',        price: 299,  mrp: 450,  discount: 34, rating: 4.7, reviews: 3456, stock: 60,  brand: 'Camlin',     image: imgBase('art1'),    description: '12 vibrant acrylic colours for canvas, paper and fabric painting.', tags: ['acrylic', 'colours', 'camlin'] },
  { id: 35,  name: 'Faber-Castell Sketch Pens (48 set)', category: 'art',        price: 449,  mrp: 699,  discount: 36, rating: 4.8, reviews: 5678, stock: 45,  brand: 'Faber-Castell', image: imgBase('art2'),  description: '48 bright water-based sketch pen colours. Non-toxic and kid-safe.', tags: ['sketch pens', '48 colors', 'faber castell'] },
  { id: 36,  name: 'Camlin Watercolour Cake Set 24',     category: 'art',        price: 199,  mrp: 320,  discount: 38, rating: 4.6, reviews: 3214, stock: 80,  brand: 'Camlin',     image: imgBase('art3'),    description: '24 brilliant watercolour cakes with brush. Perfect for school art.', tags: ['watercolour', 'cake', 'camlin'] },
  { id: 37,  name: 'Staedtler Oil Pastels 24 Shades',    category: 'art',        price: 249,  mrp: 380,  discount: 34, rating: 4.7, reviews: 2345, stock: 60,  brand: 'Staedtler',  image: imgBase('art4'),    description: '24 vivid oil pastels for smooth blending. Great for all ages.', tags: ['oil pastels', '24 shades', 'staedtler'] },
  { id: 38,  name: 'Chart Paper Pack (10 assorted)',     category: 'art',        price: 49,   mrp: 75,   discount: 35, rating: 4.4, reviews: 4567, stock: 300, brand: 'Solo',       image: imgBase('art5'),    description: '10 colourful chart papers in assorted shades. A3 size.', tags: ['chart paper', 'assorted', 'pack of 10'] },
  { id: 39,  name: 'Fevicol MR Adhesive 200g',           category: 'art',        price: 89,   mrp: 130,  discount: 32, rating: 4.8, reviews: 8765, stock: 200, brand: 'Fevicol',    image: imgBase('art6'),    description: 'Multi-purpose synthetic resin adhesive. Safe for kids. 200g pack.', tags: ['fevicol', 'glue', 'adhesive'] },
  { id: 40,  name: 'Glitter Foam Sheets (12 colours)',   category: 'art',        price: 149,  mrp: 220,  discount: 32, rating: 4.5, reviews: 2134, stock: 100, brand: 'Solo',       image: imgBase('art7'),    description: '12 glitter foam sheets for craft, decoration and school projects.', tags: ['glitter foam', 'craft', 'decoration'] },
  { id: 41,  name: 'Geometry Box (Classmate Pro)',        category: 'school',     price: 179,  mrp: 260,  discount: 31, rating: 4.7, reviews: 6543, stock: 150, brand: 'Classmate',  image: imgBase('art8'),    description: 'Complete geometry box with compass, divider, protractor, set squares and ruler.', tags: ['geometry box', 'compass', 'classmate'] },
  { id: 42,  name: 'Maped Geometry Box Metallic',        category: 'school',     price: 249,  mrp: 380,  discount: 34, rating: 4.8, reviews: 4321, stock: 80,  brand: 'Maped',      image: imgBase('art9'),    description: 'Premium metallic geometry box with precision instruments.', tags: ['geometry box', 'metallic', 'maped'] },

  // ── SCHOOL SUPPLIES ──────────────────────────────────────
  { id: 43,  name: 'School Bag (Class 1–5) Cartoon',    category: 'school',     price: 599,  mrp: 999,  discount: 40, rating: 4.5, reviews: 3456, stock: 40,  brand: 'Solo',       image: imgBase('school1'), description: 'Lightweight ergonomic school bag with colourful cartoon print. Water-resistant.', tags: ['school bag', 'kids', 'cartoon'] },
  { id: 44,  name: 'Scientific Calculator Casio fx-82',  category: 'school',     price: 899,  mrp: 1299, discount: 31, rating: 4.9, reviews: 7654, stock: 30,  brand: 'Casio',      image: imgBase('school2'), description: 'Casio fx-82 scientific calculator — 240 functions. Perfect for Class 10 to college.', tags: ['calculator', 'casio', 'scientific'] },
  { id: 45,  name: 'Stapler + 1000 Pins Set',           category: 'school',     price: 129,  mrp: 195,  discount: 34, rating: 4.6, reviews: 4567, stock: 100, brand: 'Kores',      image: imgBase('school3'), description: 'Heavy-duty mini stapler with 1000 pins. Ideal for office and school.', tags: ['stapler', 'pins', 'kores'] },
  { id: 46,  name: 'Sticky Notes (6 colour packs)',      category: 'office',     price: 79,   mrp: 120,  discount: 34, rating: 4.5, reviews: 3456, stock: 200, brand: 'Solo',       image: imgBase('school4'), description: '400 sticky notes in 6 bright colors. 75x75mm size.', tags: ['sticky notes', 'post it', '6 color'] },
  { id: 47,  name: 'Scotch Tape Set (3 pack)',           category: 'school',     price: 59,   mrp: 90,   discount: 34, rating: 4.4, reviews: 2345, stock: 300, brand: '3M',         image: imgBase('school5'), description: 'Pack of 3 transparent scotch tapes. 18mm wide, 33m each roll.', tags: ['scotch tape', 'transparent', '3m'] },
  { id: 48,  name: 'Index File (A4, 40 pockets)',        category: 'office',     price: 199,  mrp: 320,  discount: 38, rating: 4.6, reviews: 2134, stock: 60,  brand: 'Solo',       image: imgBase('school6'), description: 'Polypropylene file with 40 clear pockets. Anti-skid cover.', tags: ['file', 'a4', '40 pockets'] },
  { id: 49,  name: 'Eraser Pack (12 pcs, Apsara)',       category: 'stationery', price: 45,   mrp: 70,   discount: 36, rating: 4.5, reviews: 5678, stock: 500, brand: 'Apsara',     image: imgBase('school7'), description: '12 dust-free erasers that leave no smudge. Ideal for exams.', tags: ['eraser', 'apsara', 'pack of 12'] },
  { id: 50,  name: 'Sharpener Double-Hole (Pack 10)',    category: 'stationery', price: 35,   mrp: 55,   discount: 36, rating: 4.4, reviews: 3456, stock: 400, brand: 'Natraj',     image: imgBase('school8'), description: 'Double-hole sharpener for standard and thick pencils. Pack of 10.', tags: ['sharpener', 'double hole', 'pack 10'] },
  { id: 51,  name: 'Scale Ruler Set (30cm + 15cm)',      category: 'school',     price: 49,   mrp: 75,   discount: 35, rating: 4.5, reviews: 4321, stock: 300, brand: 'Classmate',  image: imgBase('school9'), description: 'Transparent plastic ruler set with centimeter and inch markings.', tags: ['ruler', 'scale', 'classmate'] },
  { id: 52,  name: 'Correction Fluid Pen (Whitener)',    category: 'stationery', price: 39,   mrp: 60,   discount: 35, rating: 4.4, reviews: 2876, stock: 200, brand: 'Camel',      image: imgBase('school10'),description: 'Quick-dry whitener correction pen for clean corrections.', tags: ['whitener', 'correction', 'camel'] },

  // ── TOYS ─────────────────────────────────────────────────
  { id: 53,  name: 'LEGO Classic Creative Bricks Set',   category: 'toys',       price: 1299, mrp: 2199, discount: 41, rating: 4.9, reviews: 8765, stock: 25,  brand: 'LEGO',       image: imgBase('toy1'),    description: '480-piece classic LEGO brick set for unlimited creative building. Ages 4+.', tags: ['lego', 'bricks', 'building'] },
  { id: 54,  name: 'Rubik\'s Cube (Original 3x3)',       category: 'toys',       price: 299,  mrp: 499,  discount: 40, rating: 4.7, reviews: 5432, stock: 60,  brand: 'Rubik\'s',   image: imgBase('toy2'),    description: 'The original 3x3 Rubik\'s Cube. Premium smooth-turning mechanism.', tags: ['rubiks cube', 'puzzle', 'brain'] },
  { id: 55,  name: 'Hot Wheels Car Pack (10 cars)',       category: 'toys',       price: 799,  mrp: 1299, discount: 38, rating: 4.6, reviews: 6543, stock: 35,  brand: 'Hot Wheels', image: imgBase('toy3'),    description: '10 die-cast Hot Wheels cars in assorted models. Ages 3+.', tags: ['hot wheels', 'cars', 'die cast'] },
  { id: 56,  name: 'Soft Plush Teddy Bear 40cm',         category: 'toys',       price: 499,  mrp: 850,  discount: 41, rating: 4.8, reviews: 4321, stock: 40,  brand: 'Hamleys',    image: imgBase('toy4'),    description: 'Super soft 40cm teddy bear in brown and white. Perfect gift for kids.', tags: ['teddy bear', 'plush', 'soft toy'] },
  { id: 57,  name: 'Remote Control Car 1:16 Scale',      category: 'toys',       price: 1499, mrp: 2499, discount: 40, rating: 4.5, reviews: 3456, stock: 20,  brand: 'Toyzone',    image: imgBase('toy5'),    description: 'High-speed RC car with 4-wheel drive, rechargeable battery. Range: 30m.', tags: ['rc car', 'remote control', 'rechargeable'] },
  { id: 58,  name: 'Doll House Playset (72 pieces)',      category: 'toys',       price: 1199, mrp: 1999, discount: 40, rating: 4.6, reviews: 2345, stock: 15,  brand: 'Barbie',     image: imgBase('toy6'),    description: 'Complete dollhouse with furniture, dolls and accessories. Ages 3+.', tags: ['dollhouse', 'barbie', 'playset'] },
  { id: 59,  name: 'Magnetic Drawing Board',              category: 'toys',       price: 399,  mrp: 650,  discount: 39, rating: 4.7, reviews: 5678, stock: 50,  brand: 'Toyzone',    image: imgBase('toy7'),    description: 'Mess-free magnetic drawing board with stampers. Ages 2+.', tags: ['drawing board', 'magnetic', 'kids'] },
  { id: 60,  name: 'Play-Doh 10 Colour Set',             category: 'toys',       price: 599,  mrp: 999,  discount: 40, rating: 4.8, reviews: 7654, stock: 45,  brand: 'Play-Doh',   image: imgBase('toy8'),    description: 'Non-toxic Play-Doh in 10 vibrant colors. Stimulates creativity. Ages 2+.', tags: ['play doh', 'clay', 'modelling'] },
  { id: 61,  name: 'Wooden Puzzles (100 pieces)',         category: 'toys',       price: 349,  mrp: 599,  discount: 42, rating: 4.6, reviews: 3456, stock: 30,  brand: 'Funskool',   image: imgBase('toy9'),    description: '100-piece wooden jigsaw puzzle with vibrant animal print. Ages 4+.', tags: ['puzzle', 'wooden', 'jigsaw'] },
  { id: 62,  name: 'Action Figure Superhero Set (5pc)',   category: 'toys',       price: 699,  mrp: 1199, discount: 42, rating: 4.5, reviews: 4321, stock: 25,  brand: 'Hasbro',     image: imgBase('toy10'),   description: '5 superhero action figures — detailed articulation. Ages 4+.', tags: ['action figure', 'superhero', 'hasbro'] },

  // ── GAMES ────────────────────────────────────────────────
  { id: 63,  name: 'Scrabble Classic Board Game',        category: 'games',      price: 999,  mrp: 1699, discount: 41, rating: 4.8, reviews: 5432, stock: 20,  brand: 'Mattel',     image: imgBase('game1'),   description: 'Classic Scrabble word game for 2–4 players. Great for families.', tags: ['scrabble', 'word game', 'family'] },
  { id: 64,  name: 'Ludo + Snakes & Ladders Combo',      category: 'games',      price: 299,  mrp: 499,  discount: 40, rating: 4.6, reviews: 8765, stock: 60,  brand: 'Funskool',   image: imgBase('game2'),   description: 'Deluxe Ludo and Snakes & Ladders board game combo. For all ages.', tags: ['ludo', 'snakes ladders', 'board game'] },
  { id: 65,  name: 'Chess Set (Magnetic Travel)',        category: 'games',      price: 499,  mrp: 850,  discount: 41, rating: 4.7, reviews: 4321, stock: 30,  brand: 'Staunton',   image: imgBase('game3'),   description: 'Magnetic travel chess set with folding board. Perfect for trips.', tags: ['chess', 'magnetic', 'travel'] },
  { id: 66,  name: 'UNO Card Game Original',             category: 'games',      price: 349,  mrp: 599,  discount: 42, rating: 4.9, reviews: 9876, stock: 80,  brand: 'Mattel',     image: imgBase('game4'),   description: 'Original UNO card game — 112 cards with special action cards.', tags: ['uno', 'card game', 'mattel'] },
  { id: 67,  name: 'Monopoly Classic Edition',           category: 'games',      price: 799,  mrp: 1399, discount: 43, rating: 4.7, reviews: 6543, stock: 20,  brand: 'Hasbro',     image: imgBase('game5'),   description: 'Classic Monopoly board game. Build properties and become a millionaire!', tags: ['monopoly', 'board game', 'hasbro'] },
  { id: 68,  name: 'Jenga Classic Wooden Blocks',        category: 'games',      price: 599,  mrp: 999,  discount: 40, rating: 4.8, reviews: 5678, stock: 25,  brand: 'Hasbro',     image: imgBase('game6'),   description: 'Original Jenga with 54 hardwood blocks. The skill and strategy game.', tags: ['jenga', 'wooden', 'skill game'] },
  { id: 69,  name: 'Carrom Board (Full Size, 4mm)',      category: 'games',      price: 1499, mrp: 2499, discount: 40, rating: 4.6, reviews: 4321, stock: 10,  brand: 'Syndicate',  image: imgBase('game7'),   description: 'Full size 74x74cm carrom board with 4mm thickness. Comes with coins and striker.', tags: ['carrom', 'board', 'full size'] },
  { id: 70,  name: 'Badminton Racket Set (2 rackets)',   category: 'games',      price: 799,  mrp: 1299, discount: 38, rating: 4.5, reviews: 3456, stock: 30,  brand: 'Yonex',      image: imgBase('game8'),   description: '2 Yonex-style badminton rackets with 3 shuttlecocks. Great for beginners.', tags: ['badminton', 'racket', 'sports'] },

  // ── GIFTS ────────────────────────────────────────────────
  { id: 71,  name: 'Greeting Card Pack (Birthday x12)',  category: 'gifts',      price: 149,  mrp: 250,  discount: 40, rating: 4.6, reviews: 4321, stock: 100, brand: 'Archies',    image: imgBase('gift1'),   description: 'Pack of 12 premium birthday greeting cards with envelopes.', tags: ['greeting cards', 'birthday', 'pack of 12'] },
  { id: 72,  name: 'Gift Wrap Paper Roll (6 designs)',   category: 'gifts',      price: 199,  mrp: 350,  discount: 43, rating: 4.5, reviews: 2345, stock: 80,  brand: 'Solo',       image: imgBase('gift2'),   description: '6 beautiful gift wrap designs on rolls. Perfect for all occasions.', tags: ['gift wrap', 'wrapping paper', '6 designs'] },
  { id: 73,  name: 'Ribbon & Bow Set (30 pcs)',          category: 'gifts',      price: 99,   mrp: 175,  discount: 43, rating: 4.4, reviews: 1876, stock: 150, brand: 'Solo',       image: imgBase('gift3'),   description: '30 pieces of assorted ribbons and bows for gift decoration.', tags: ['ribbon', 'bow', 'gift decoration'] },
  { id: 74,  name: 'Gift Box Set (3 sizes, 5 boxes)',    category: 'gifts',      price: 249,  mrp: 420,  discount: 41, rating: 4.6, reviews: 3456, stock: 60,  brand: 'Solo',       image: imgBase('gift4'),   description: '5 premium gift boxes in 3 sizes with lids. Assorted colors.', tags: ['gift box', 'premium', 'assorted'] },
  { id: 75,  name: 'Personalized Pen Gift Set',          category: 'gifts',      price: 399,  mrp: 650,  discount: 39, rating: 4.7, reviews: 2876, stock: 40,  brand: 'Parker',     image: imgBase('gift5'),   description: 'Premium pen gift set in a beautiful box. Perfect corporate gift.', tags: ['pen gift', 'corporate', 'premium'] },
  { id: 76,  name: 'Photo Frame (5x7) Golden Border',    category: 'gifts',      price: 299,  mrp: 499,  discount: 40, rating: 4.5, reviews: 2134, stock: 50,  brand: 'Archies',    image: imgBase('gift6'),   description: '5x7 inch photo frame with golden border. Table and wall mountable.', tags: ['photo frame', 'golden', '5x7'] },
  { id: 77,  name: 'Tissue Paper (Decorative, 50 sheets)',category: 'gifts',     price: 89,   mrp: 150,  discount: 41, rating: 4.4, reviews: 1654, stock: 120, brand: 'Solo',       image: imgBase('gift7'),   description: '50 sheets of decorative tissue paper in 6 patterns for gift bags.', tags: ['tissue paper', 'decorative', 'gift bag'] },
  { id: 78,  name: 'Balloon Pack (50 pcs Latex)',        category: 'decoration', price: 99,   mrp: 175,  discount: 43, rating: 4.5, reviews: 5678, stock: 300, brand: 'Anagram',    image: imgBase('gift8'),   description: '50 high-quality latex balloons in assorted colors. Ideal for parties.', tags: ['balloons', 'latex', 'party'] },
  { id: 79,  name: 'Happy Birthday Banner Combo',        category: 'decoration', price: 149,  mrp: 250,  discount: 40, rating: 4.6, reviews: 3456, stock: 80,  brand: 'Solo',       image: imgBase('gift9'),   description: 'Birthday banner, star balloons, confetti and streamers combo pack.', tags: ['birthday banner', 'decoration', 'combo'] },
  { id: 80,  name: 'Scented Candles Set (6 pcs)',        category: 'decoration', price: 299,  mrp: 499,  discount: 40, rating: 4.7, reviews: 4321, stock: 40,  brand: 'Iris',       image: imgBase('gift10'),  description: '6 premium soy wax scented candles — rose, lavender, vanilla and more.', tags: ['candles', 'scented', 'soy wax'] },

  // ── FLOWERS ──────────────────────────────────────────────
  { id: 81,  name: 'Red Rose Bouquet (12 roses)',        category: 'flowers',    price: 599,  mrp: 999,  discount: 40, rating: 4.9, reviews: 5432, stock: 20,  brand: 'Fresh',      image: imgBase('flower1'), description: 'Beautiful fresh red roses arranged in a premium bouquet. Same-day delivery available.', tags: ['roses', 'red', 'bouquet'] },
  { id: 82,  name: 'Mixed Flower Arrangement',           category: 'flowers',    price: 799,  mrp: 1399, discount: 43, rating: 4.8, reviews: 3456, stock: 15,  brand: 'Fresh',      image: imgBase('flower2'), description: 'Premium mixed flower arrangement with lilies, roses and carnations.', tags: ['mixed flowers', 'arrangement', 'premium'] },
  { id: 83,  name: 'Artificial Flower Bunch (Silk)',     category: 'flowers',    price: 299,  mrp: 499,  discount: 40, rating: 4.6, reviews: 2345, stock: 50,  brand: 'Craftghar',  image: imgBase('flower3'), description: 'Realistic silk artificial flower bunch. No maintenance needed. Great for decoration.', tags: ['artificial flowers', 'silk', 'decoration'] },
  { id: 84,  name: 'Sunflower Bouquet (8 stems)',        category: 'flowers',    price: 449,  mrp: 750,  discount: 40, rating: 4.7, reviews: 2876, stock: 12,  brand: 'Fresh',      image: imgBase('flower4'), description: '8 bright fresh sunflowers in a gift-ready bouquet.', tags: ['sunflower', 'bouquet', 'yellow'] },
  { id: 85,  name: 'Desktop Mini Succulent Plant',       category: 'flowers',    price: 199,  mrp: 349,  discount: 43, rating: 4.8, reviews: 4321, stock: 30,  brand: 'Ugaoo',      image: imgBase('flower5'), description: 'Easy-care desktop succulent in a cute pot. Perfect for gifting.', tags: ['succulent', 'plant', 'desktop'] },
  { id: 86,  name: 'Rose & Lily Combo Bouquet',         category: 'flowers',    price: 699,  mrp: 1199, discount: 42, rating: 4.9, reviews: 3210, stock: 10,  brand: 'Fresh',      image: imgBase('flower6'), description: 'A beautiful combination of red roses and white lilies for special occasions.', tags: ['rose', 'lily', 'combo'] },

  // ── OFFICE SUPPLIES ──────────────────────────────────────
  { id: 87,  name: 'Spiral Binder A4 (Pack of 5)',       category: 'office',     price: 249,  mrp: 399,  discount: 38, rating: 4.5, reviews: 2134, stock: 80,  brand: 'Solo',       image: imgBase('office1'), description: 'A4 spiral binders with 100 pages each. Pack of 5.', tags: ['binder', 'spiral', 'a4'] },
  { id: 88,  name: 'Desk Organiser (5 compartments)',    category: 'office',     price: 399,  mrp: 650,  discount: 39, rating: 4.6, reviews: 2876, stock: 35,  brand: 'Solo',       image: imgBase('office2'), description: '5-compartment desk organiser for pens, files and office supplies.', tags: ['desk organiser', 'office', 'storage'] },
  { id: 89,  name: 'Printer Paper A4 (500 sheets)',      category: 'office',     price: 399,  mrp: 600,  discount: 34, rating: 4.7, reviews: 4567, stock: 100, brand: 'JK',         image: imgBase('office3'), description: 'JK Copier 75 GSM A4 printer paper. 500 sheets per ream.', tags: ['printer paper', 'a4', 'jk copier'] },
  { id: 90,  name: 'Whiteboard Marker Set (12 pcs)',     category: 'office',     price: 199,  mrp: 320,  discount: 38, rating: 4.6, reviews: 3456, stock: 60,  brand: 'Camlin',     image: imgBase('office4'), description: '12 dry-erase whiteboard markers in assorted colors. Washable.', tags: ['whiteboard', 'marker', 'dry erase'] },
  { id: 91,  name: 'Lever Arch File (A4, Pack 2)',       category: 'office',     price: 299,  mrp: 499,  discount: 40, rating: 4.5, reviews: 2345, stock: 50,  brand: 'Solo',       image: imgBase('office5'), description: 'Heavy-duty lever arch files for document storage. Pack of 2.', tags: ['lever arch', 'file', 'document'] },
  { id: 92,  name: 'Business Card Holder (100 cards)',   category: 'office',     price: 149,  mrp: 249,  discount: 40, rating: 4.4, reviews: 1654, stock: 40,  brand: 'Solo',       image: imgBase('office6'), description: 'Transparent business card holder with 100 card capacity.', tags: ['business card', 'holder', 'office'] },

  // ── ADDITIONAL PRODUCTS ──────────────────────────────────
  { id: 93,  name: 'Lunch Box (3 tier, Steel)',          category: 'school',     price: 699,  mrp: 1199, discount: 42, rating: 4.7, reviews: 5678, stock: 30,  brand: 'Milton',     image: imgBase('extra1'),  description: '3-tier stainless steel lunch box. Leak-proof and easy to clean.', tags: ['lunch box', 'steel', 'milton'] },
  { id: 94,  name: 'Water Bottle (1L, Tritan)',          category: 'school',     price: 499,  mrp: 850,  discount: 41, rating: 4.8, reviews: 6543, stock: 50,  brand: 'Nalgene',    image: imgBase('extra2'),  description: 'BPA-free Tritan plastic 1-litre sports water bottle with flip lid.', tags: ['water bottle', 'tritan', '1 litre'] },
  { id: 95,  name: 'Pencil Pouch (Zipper, 3 pockets)',  category: 'school',     price: 199,  mrp: 350,  discount: 43, rating: 4.6, reviews: 4321, stock: 80,  brand: 'Classmate',  image: imgBase('extra3'),  description: 'Large 3-pocket pencil pouch with transparent front. Water-resistant.', tags: ['pencil pouch', 'zipper', 'classmate'] },
  { id: 96,  name: 'Hindi Grammar Book Class 6–8',       category: 'books',      price: 149,  mrp: 250,  discount: 40, rating: 4.5, reviews: 2134, stock: 40,  brand: 'S.Chand',    image: imgBase('extra4'),  description: 'Complete Hindi grammar and composition for Classes 6 to 8.', tags: ['hindi grammar', 'class 6-8', 'schand'] },
  { id: 97,  name: 'English Grammar (Wren & Martin)',    category: 'books',      price: 349,  mrp: 599,  discount: 42, rating: 4.9, reviews: 12345,stock: 45,  brand: 'S.Chand',    image: imgBase('extra5'),  description: 'The legendary Wren & Martin High School English Grammar book.', tags: ['english grammar', 'wren martin', 'schand'] },
  { id: 98,  name: 'Colorful Washi Tape Set (20 rolls)', category: 'art',        price: 299,  mrp: 499,  discount: 40, rating: 4.7, reviews: 3456, stock: 60,  brand: 'Solo',       image: imgBase('extra6'),  description: '20 rolls of decorative washi tape in various patterns. Great for scrapbooking.', tags: ['washi tape', 'decorative', 'scrapbook'] },
  { id: 99,  name: 'Mini Stapler + 500 Staples',        category: 'stationery', price: 89,   mrp: 140,  discount: 36, rating: 4.5, reviews: 4567, stock: 150, brand: 'Kores',      image: imgBase('extra7'),  description: 'Compact mini stapler with 500 staples. Great for home and school use.', tags: ['stapler', 'mini', 'kores'] },
  { id: 100, name: 'Page Flags / Tab Stickers (300 pcs)',category: 'stationery', price: 59,   mrp: 99,   discount: 40, rating: 4.5, reviews: 3210, stock: 250, brand: 'Solo',       image: imgBase('extra8'),  description: '300 transparent sticky tab page flags in 5 neon colors.', tags: ['page flags', 'tabs', 'sticky'] },
  { id: 101, name: 'Maths Activity Kit (Class 1–5)',     category: 'toys',       price: 499,  mrp: 850,  discount: 41, rating: 4.8, reviews: 4321, stock: 25,  brand: 'Orbo',       image: imgBase('extra9'),  description: 'Complete maths activity kit with abacus, number cards, shapes and more.', tags: ['maths kit', 'activity', 'kids'] },
  { id: 102, name: 'Hindi Story Books Set (5 books)',    category: 'books',      price: 299,  mrp: 499,  discount: 40, rating: 4.7, reviews: 2876, stock: 30,  brand: 'Rajpal',     image: imgBase('extra10'), description: '5 popular Hindi story books for children aged 6–12.', tags: ['hindi stories', 'kids books', 'rajpal'] },
  { id: 103, name: 'Flash Cards (Alphabet + Numbers)',   category: 'toys',       price: 199,  mrp: 350,  discount: 43, rating: 4.8, reviews: 5432, stock: 60,  brand: 'Orbo',       image: imgBase('extra11'), description: '104 educational flash cards covering A-Z and 0-100. Laminated, durable.', tags: ['flash cards', 'alphabet', 'numbers'] },
  { id: 104, name: 'Foam Stickers Sheet Pack (10 pcs)', category: 'art',        price: 79,   mrp: 130,  discount: 39, rating: 4.5, reviews: 2134, stock: 120, brand: 'Solo',       image: imgBase('extra12'), description: '10 sheets of foam stickers with animals, alphabets and shapes.', tags: ['foam stickers', 'kids', 'craft'] },
  { id: 105, name: 'Origami Paper 200 sheets (20 clr)', category: 'art',        price: 149,  mrp: 249,  discount: 40, rating: 4.7, reviews: 3456, stock: 80,  brand: 'Solo',       image: imgBase('extra13'), description: '200 sheets of square origami paper in 20 vibrant colors. 15x15cm.', tags: ['origami', 'paper', '20 colors'] },
];

export const OFFERS = [
  { id: 1, code: 'BACK2SCHOOL', discount: 20, type: 'percent', minOrder: 299,  description: '20% off on School Supplies', category: 'school' },
  { id: 2, code: 'BOOKFAIR25',  discount: 25, type: 'percent', minOrder: 499,  description: '25% off on All Books',        category: 'books'  },
  { id: 3, code: 'FLAT50',      discount: 50, type: 'flat',    minOrder: 199,  description: 'Flat ₹50 Off on Any Order',  category: null     },
  { id: 4, code: 'FIRSTBUY',    discount: 15, type: 'percent', minOrder: 0,    description: '15% off on First Purchase',  category: null     },
  { id: 5, code: 'GIFT10',      discount: 10, type: 'percent', minOrder: 399,  description: '10% off on Gift Items',      category: 'gifts'  },
];

export const BANNERS = [
  { id: 1, title: 'Back To School Sale!',         subtitle: 'Flat 20% OFF on all School Supplies', cta: 'Shop Now',   category: 'school',  gradient: 'linear-gradient(135deg, #2874F0 0%, #0052CC 100%)',   badge: '20% OFF' },
  { id: 2, title: 'Latest NCERT Books In Stock!', subtitle: 'All Classes Available — Limited Stock',cta: 'Buy Now',   category: 'ncert',   gradient: 'linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)',   badge: 'New Stock' },
  { id: 3, title: 'New Gift Collection 🎁',        subtitle: 'Unique Gifts for Every Occasion',     cta: 'Explore',   category: 'gifts',   gradient: 'linear-gradient(135deg, #EC4899 0%, #BE185D 100%)',   badge: 'New!' },
  { id: 4, title: 'Premium Flower Collection 🌸',  subtitle: 'Fresh Flowers • Bouquets • Plants',   cta: 'Shop Flowers',category:'flowers',  gradient: 'linear-gradient(135deg, #E11D48 0%, #9F1239 100%)',   badge: 'Fresh Daily' },
  { id: 5, title: 'Trending Toys & Games 🎮',      subtitle: 'Up to 43% OFF • All Ages',           cta: 'View All',  category: 'toys',    gradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',   badge: 'Up to 43% Off' },
];

export const TESTIMONIALS = [
  { id: 1, name: 'Priya Sharma',    avatar: imgBase('face1',60,60), rating: 5, text: 'Best stationery shop in town! Got all my NCERT books and art supplies in one place.', date: '2 days ago' },
  { id: 2, name: 'Rahul Gupta',     avatar: imgBase('face2',60,60), rating: 5, text: 'Excellent quality products at very affordable prices. Fast delivery too!', date: '1 week ago' },
  { id: 3, name: 'Anjali Singh',    avatar: imgBase('face3',60,60), rating: 4, text: 'Ordered gifts and flowers for my sister\'s birthday — beautifully packaged!', date: '3 days ago' },
  { id: 4, name: 'Mohit Verma',     avatar: imgBase('face4',60,60), rating: 5, text: 'Great toy collection! My kids love the LEGO set I bought from here.', date: '5 days ago' },
];

export const ADMIN_STATS = {
  totalOrders: 1247,
  totalRevenue: 189450,
  totalProducts: 105,
  totalCustomers: 892,
  pendingOrders: 23,
  revenueGrowth: 18.5,
  ordersGrowth: 12.3,
  customersGrowth: 8.7,
};
